// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


import { CustomerOrderForDeliveryBase } from './customer-order-for-delivery-base';
import { CustomerOrderForPickupBase } from './customer-order-for-pickup-base';
import { DiscountBase } from './discount-base';
import { LoyaltyRewardBase } from './loyalty-reward-base';
import { MerchandiseHierarchyCommonData } from './merchandise-hierarchy-common-data';
import { PromotionExternalTriggerType } from './promotion-external-trigger-type';
import { PromotionManualTriggerType } from './promotion-manual-trigger-type';
import { ReturnBase } from './return-base';
import { ReturnForDeliveryBase } from './return-for-delivery-base';
import { ReturnForPickupBase } from './return-for-pickup-base';
import { SaleBase } from './sale-base';
import { SaleForDeliveryBase } from './sale-for-delivery-base';
import { SaleForPickupBase } from './sale-for-pickup-base';
import { TenderCouponBase } from './tender-coupon-base';

/**
 * Depending on the type of the line item, one of the contained elements like Sales, SaleForDelivery must be filled.
 * @export
 * @interface LineItemDomainSpecific
 */
export interface LineItemDomainSpecific {
    /**
     * This is currently not supported
     * @type {object}
     * @memberof LineItemDomainSpecific
     */
    any?: object;
    /**
     * 
     * @type {SaleBase}
     * @memberof LineItemDomainSpecific
     */
    Sale?: SaleBase;
    /**
     * 
     * @type {SaleForDeliveryBase}
     * @memberof LineItemDomainSpecific
     */
    SaleForDelivery?: SaleForDeliveryBase;
    /**
     * 
     * @type {SaleForPickupBase}
     * @memberof LineItemDomainSpecific
     */
    SaleForPickup?: SaleForPickupBase;
    /**
     * 
     * @type {ReturnBase}
     * @memberof LineItemDomainSpecific
     */
    Return?: ReturnBase;
    /**
     * 
     * @type {ReturnForDeliveryBase}
     * @memberof LineItemDomainSpecific
     */
    ReturnForDelivery?: ReturnForDeliveryBase;
    /**
     * 
     * @type {ReturnForPickupBase}
     * @memberof LineItemDomainSpecific
     */
    ReturnForPickup?: ReturnForPickupBase;
    /**
     * 
     * @type {CustomerOrderForDeliveryBase}
     * @memberof LineItemDomainSpecific
     */
    CustomerOrderForDelivery?: CustomerOrderForDeliveryBase;
    /**
     * 
     * @type {CustomerOrderForPickupBase}
     * @memberof LineItemDomainSpecific
     */
    CustomerOrderForPickup?: CustomerOrderForPickupBase;
    /**
     * 
     * @type {DiscountBase}
     * @memberof LineItemDomainSpecific
     */
    Discount?: DiscountBase;
    /**
     * 
     * @type {LoyaltyRewardBase}
     * @memberof LineItemDomainSpecific
     */
    LoyaltyReward?: LoyaltyRewardBase;
    /**
     * 
     * @type {TenderCouponBase}
     * @memberof LineItemDomainSpecific
     */
    Coupon?: TenderCouponBase;
    /**
     * 
     * @type {PromotionManualTriggerType}
     * @memberof LineItemDomainSpecific
     */
    PromotionManualTrigger?: PromotionManualTriggerType;
    /**
     * 
     * @type {PromotionExternalTriggerType}
     * @memberof LineItemDomainSpecific
     */
    PromotionExternalTrigger?: PromotionExternalTriggerType;
    /**
     * Identifies the line item. Although this is an array, exactly 1 entry is required.
     * @type {Array<number>}
     * @memberof LineItemDomainSpecific
     */
    SequenceNumber?: Array<number>;
    /**
     * This information is taken for checking eligibilities on item hierarchy level.
     * @type {Array<MerchandiseHierarchyCommonData>}
     * @memberof LineItemDomainSpecific
     */
    MerchandiseHierarchy?: Array<MerchandiseHierarchyCommonData>;
}


