// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoyaltyAccountType } from './loyalty-account-type';

/**
 * 
 * @export
 * @interface LoyaltyAccountCommonData
 */
export interface LoyaltyAccountCommonData {
    /**
     * Identifies the customer of the loyalty account. Must be set, but currently the value is not used.
     * @type {string}
     * @memberof LoyaltyAccountCommonData
     */
    CustomerID?: string;
    /**
     * List of loyalty programs to which this customer is assigned for this loyalty account.
     * @type {Array<LoyaltyAccountType>}
     * @memberof LoyaltyAccountCommonData
     */
    LoyaltyProgram?: Array<LoyaltyAccountType>;
    /**
     * Indicates if the specified customer is also an employee. Currently not used.
     * @type {boolean}
     * @memberof LoyaltyAccountCommonData
     */
    CustomerIsEmployeeFlag?: boolean;
}


