// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



/**
 * The price of the line item after the price derivation rule was applied.
 * @export
 * @interface NewPrice
 */
export interface NewPrice {
    /**
     * 
     * @type {number}
     * @memberof NewPrice
     */
    value?: number;
    /**
     * Uppercase currency is expected in uppercase ISO format.
     * @type {string}
     * @memberof NewPrice
     */
    Currency?: string;
}


