// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ARTSCommonHeaderType } from './artscommon-header-type';
import { PriceCalculateBase } from './price-calculate-base';

/**
 * Request sent by the client. Contains all relevant information for the price calculation.
 * @export
 * @interface PriceCalculate
 */
export interface PriceCalculate {
    /**
     * 
     * @type {ARTSCommonHeaderType}
     * @memberof PriceCalculate
     */
    ARTSHeader: ARTSCommonHeaderType;
    /**
     * Contains the items for which a price calculation should be performed and additional information about how it is performed.
     * @type {Array<PriceCalculateBase>}
     * @memberof PriceCalculate
     */
    PriceCalculateBody: Array<PriceCalculateBase>;
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof PriceCalculate
     */
    any?: Array<object>;
    /**
     * Major version of the Client API version to be used. For Client API version X.Y, this field corresponds to the X part. Currently allowed versions of the Client API are 1.0, 2.0, 2.1. and 3.0. In a cloud environment, only version 2.1 or higher may be used. 
     * @type {number}
     * @memberof PriceCalculate
     */
    InternalMajorVersion: number;
    /**
     * Minor version of the Client API version to be used. For Client API version X.Y, this field corresponds to the Y part.
     * @type {number}
     * @memberof PriceCalculate
     */
    InternalMinorVersion?: number;
}


