// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains information about the consumed eligibility if this was a coupon eligibility.
 * @export
 * @interface PriceDerivationRuleEligibility
 */
export interface PriceDerivationRuleEligibility {
    /**
     * Contains the coupon code for a coupon eligibility.
     * @type {string}
     * @memberof PriceDerivationRuleEligibility
     */
    ReferenceID?: string;
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof PriceDerivationRuleEligibility
     */
    any?: Array<object>;
    /**
     * The sequence number of the line item containing the coupon for a coupon eligibility.
     * @type {number}
     * @memberof PriceDerivationRuleEligibility
     */
    ReferenceSequenceNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof PriceDerivationRuleEligibility
     */
    Type: PriceDerivationRuleEligibilityTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PriceDerivationRuleEligibilityTypeEnum {
    StoreCoupon = 'StoreCoupon'
}



