// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


import { AmountCommonData } from './amount-common-data';

/**
 * Information provided by the client for a manual promotion that is to be calculated. Contains eligibility relevant information and protentially also the specification of a discount (depending on the privilege type). 
 * @export
 * @interface PromotionManualTriggerType
 */
export interface PromotionManualTriggerType {
    /**
     * Identifies the manual trigger per line item. Must be a positive small integer.
     * @type {number}
     * @memberof PromotionManualTriggerType
     */
    ManualTriggerSequenceNumber: number;
    /**
     * Type of the manual trigger as defined in the promotion master data. This type is to be set by the client and used to determine relevant promotions.
     * @type {string}
     * @memberof PromotionManualTriggerType
     */
    ManualTriggerType: string;
    /**
     * Value for the manual trigger as defined in the promotion master data. This value is to be set by the client and used to determine relevant promotions.
     * @type {string}
     * @memberof PromotionManualTriggerType
     */
    ManualTriggerValue: string;
    /**
     * Specifies the type of the price adjustment. Valid values are: Absolute discount (RS), percentage discount (RP), new price (PS) or the reduction specified in the promotion master data (AM). 
     * @type {string}
     * @memberof PromotionManualTriggerType
     */
    PrivilegeType: PromotionManualTriggerTypePrivilegeTypeEnum;
    /**
     * 
     * @type {AmountCommonData}
     * @memberof PromotionManualTriggerType
     */
    PrivilegeValue: AmountCommonData;
    /**
     * A value that is to be added to the sequence of the promotion price derivation rule. This allows to apply multiple manual discounts with the same price derivation rule. 
     * @type {number}
     * @memberof PromotionManualTriggerType
     */
    ManualTriggerSequenceAddend: number;
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof PromotionManualTriggerType
     */
    any?: Array<object>;
}

/**
    * @export
    * @enum {string}
    */
export enum PromotionManualTriggerTypePrivilegeTypeEnum {
    AM = 'AM',
    RS = 'RS',
    RP = 'RP',
    PS = 'PS'
}



