// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



/**
 * 
 * @export
 * @interface QuantityCommonData
 */
export interface QuantityCommonData {
    /**
     * Must be an integer. The overall quantity is the product of value and units.
     * @type {number}
     * @memberof QuantityCommonData
     */
    value?: number;
    /**
     * May be fractional. Set this to one for piece like items. The overall quantity is the product of value and units.
     * @type {number}
     * @memberof QuantityCommonData
     */
    Units?: number;
    /**
     * Must match with the information specified in the promotions and regular prices. No conversion of unit of measures is done. Uppercase format.
     * @type {string}
     * @memberof QuantityCommonData
     */
    UnitOfMeasureCode?: string;
}


