// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AmountCommonData } from './amount-common-data';
import { ExtendedAmountType } from './extended-amount-type';
import { FrequentShopperPointsModifierType } from './frequent-shopper-points-modifier-type';
import { ItemID } from './item-id';
import { ItemLink } from './item-link';
import { MerchandiseHierarchyCommonData } from './merchandise-hierarchy-common-data';
import { PromotionManualTriggerType } from './promotion-manual-trigger-type';
import { PromotionPriceDerivationRuleReferenceType } from './promotion-price-derivation-rule-reference-type';
import { QuantityCommonData } from './quantity-common-data';
import { RetailPriceModifierDomainSpecific } from './retail-price-modifier-domain-specific';
import { UnitPriceCommonData } from './unit-price-common-data';

/**
 * A flavor of a line item whereby customers return an item and the store will pick it up from a location on a future date and time. ReturnForPickup is currently not supported. 
 * @export
 * @interface ReturnForPickupBase
 */
export interface ReturnForPickupBase {
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof ReturnForPickupBase
     */
    any?: Array<object>;
    /**
     * 
     * @type {Array<ItemID>}
     * @memberof ReturnForPickupBase
     */
    ItemID?: Array<ItemID>;
    /**
     * 
     * @type {Array<MerchandiseHierarchyCommonData>}
     * @memberof ReturnForPickupBase
     */
    MerchandiseHierarchy?: Array<MerchandiseHierarchyCommonData>;
    /**
     * 
     * @type {UnitPriceCommonData}
     * @memberof ReturnForPickupBase
     */
    RegularSalesUnitPrice?: UnitPriceCommonData;
    /**
     * 
     * @type {ExtendedAmountType}
     * @memberof ReturnForPickupBase
     */
    ExtendedAmount?: ExtendedAmountType;
    /**
     * 
     * @type {AmountCommonData}
     * @memberof ReturnForPickupBase
     */
    ExtendedDiscountAmount?: AmountCommonData;
    /**
     * 
     * @type {Array<QuantityCommonData>}
     * @memberof ReturnForPickupBase
     */
    Quantity?: Array<QuantityCommonData>;
    /**
     * 
     * @type {Array<RetailPriceModifierDomainSpecific>}
     * @memberof ReturnForPickupBase
     */
    RetailPriceModifier?: Array<RetailPriceModifierDomainSpecific>;
    /**
     * 
     * @type {Array<ItemLink>}
     * @memberof ReturnForPickupBase
     */
    ItemLink?: Array<ItemLink>;
    /**
     * 
     * @type {string}
     * @memberof ReturnForPickupBase
     */
    ItemType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    NonDiscountableFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    FixedPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    TaxIncludedInPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    NonPieceGoodFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    FrequentShopperPointsEligibilityFlag?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReturnForPickupBase
     */
    DiscountTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnForPickupBase
     */
    PriceTypeCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnForPickupBase
     */
    NotConsideredByPriceEngineFlag?: boolean;
    /**
     * 
     * @type {Array<FrequentShopperPointsModifierType>}
     * @memberof ReturnForPickupBase
     */
    FrequentShopperPointsModifier?: Array<FrequentShopperPointsModifierType>;
    /**
     * 
     * @type {Array<PromotionPriceDerivationRuleReferenceType>}
     * @memberof ReturnForPickupBase
     */
    PromotionPriceDerivationRuleReference?: Array<PromotionPriceDerivationRuleReferenceType>;
    /**
     * 
     * @type {Array<PromotionManualTriggerType>}
     * @memberof ReturnForPickupBase
     */
    PromotionManualTrigger?: Array<PromotionManualTriggerType>;
}


