// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



/**
 * Specifies how the regular sales price should be rounded after multiplying the unit price with the provided quantity.
 * @export
 * @interface RoundingRuleType
 */
export interface RoundingRuleType {
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof RoundingRuleType
     */
    any?: Array<object>;
    /**
     * Specifies the rounding direction. Default value is Commercial.
     * @type {string}
     * @memberof RoundingRuleType
     */
    RoundingMethod?: RoundingRuleTypeRoundingMethodEnum;
    /**
     * The rounding result must be an integer multiple of the specified value. Example: If the value to be rounded is 12.345, rounding method is Commercial and Multple is 0.05, then the rounding result is 12.35. Default value is 0.01. 
     * @type {number}
     * @memberof RoundingRuleType
     */
    Multiple?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum RoundingRuleTypeRoundingMethodEnum {
    Up = 'Up',
    Down = 'Down',
    Commercial = 'Commercial'
}



