// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


import { AmountCommonData } from './amount-common-data';
import { ExtendedAmountType } from './extended-amount-type';
import { FrequentShopperPointsModifierType } from './frequent-shopper-points-modifier-type';
import { ItemID } from './item-id';
import { ItemLink } from './item-link';
import { MerchandiseHierarchyCommonData } from './merchandise-hierarchy-common-data';
import { PromotionManualTriggerType } from './promotion-manual-trigger-type';
import { PromotionPriceDerivationRuleReferenceType } from './promotion-price-derivation-rule-reference-type';
import { QuantityCommonData } from './quantity-common-data';
import { RetailPriceModifierDomainSpecific } from './retail-price-modifier-domain-specific';
import { UnitPriceCommonData } from './unit-price-common-data';

/**
 * A flavor of a line item whereby customers purchase an item and takes it out directly. For a description of the properties see CustomerOrderForDeliveryBase. 
 * @export
 * @interface SaleBase
 */
export interface SaleBase {
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof SaleBase
     */
    any?: Array<object>;
    /**
     * 
     * @type {Array<ItemID>}
     * @memberof SaleBase
     */
    ItemID?: Array<ItemID>;
    /**
     * 
     * @type {Array<MerchandiseHierarchyCommonData>}
     * @memberof SaleBase
     */
    MerchandiseHierarchy?: Array<MerchandiseHierarchyCommonData>;
    /**
     * 
     * @type {UnitPriceCommonData}
     * @memberof SaleBase
     */
    RegularSalesUnitPrice?: UnitPriceCommonData;
    /**
     * 
     * @type {ExtendedAmountType}
     * @memberof SaleBase
     */
    ExtendedAmount?: ExtendedAmountType;
    /**
     * 
     * @type {AmountCommonData}
     * @memberof SaleBase
     */
    ExtendedDiscountAmount?: AmountCommonData;
    /**
     * 
     * @type {Array<QuantityCommonData>}
     * @memberof SaleBase
     */
    Quantity?: Array<QuantityCommonData>;
    /**
     * 
     * @type {Array<RetailPriceModifierDomainSpecific>}
     * @memberof SaleBase
     */
    RetailPriceModifier?: Array<RetailPriceModifierDomainSpecific>;
    /**
     * 
     * @type {Array<ItemLink>}
     * @memberof SaleBase
     */
    ItemLink?: Array<ItemLink>;
    /**
     * 
     * @type {string}
     * @memberof SaleBase
     */
    ItemType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    NonDiscountableFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    FixedPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    TaxIncludedInPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    NonPieceGoodFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    FrequentShopperPointsEligibilityFlag?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SaleBase
     */
    DiscountTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleBase
     */
    PriceTypeCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SaleBase
     */
    NotConsideredByPriceEngineFlag?: boolean;
    /**
     * 
     * @type {Array<FrequentShopperPointsModifierType>}
     * @memberof SaleBase
     */
    FrequentShopperPointsModifier?: Array<FrequentShopperPointsModifierType>;
    /**
     * 
     * @type {Array<PromotionPriceDerivationRuleReferenceType>}
     * @memberof SaleBase
     */
    PromotionPriceDerivationRuleReference?: Array<PromotionPriceDerivationRuleReferenceType>;
    /**
     * 
     * @type {Array<PromotionManualTriggerType>}
     * @memberof SaleBase
     */
    PromotionManualTrigger?: Array<PromotionManualTriggerType>;
}


