// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AmountCommonData } from './amount-common-data';
import { ExtendedAmountType } from './extended-amount-type';
import { FrequentShopperPointsModifierType } from './frequent-shopper-points-modifier-type';
import { ItemID } from './item-id';
import { ItemLink } from './item-link';
import { MerchandiseHierarchyCommonData } from './merchandise-hierarchy-common-data';
import { PromotionManualTriggerType } from './promotion-manual-trigger-type';
import { PromotionPriceDerivationRuleReferenceType } from './promotion-price-derivation-rule-reference-type';
import { QuantityCommonData } from './quantity-common-data';
import { RetailPriceModifierDomainSpecific } from './retail-price-modifier-domain-specific';
import { UnitPriceCommonData } from './unit-price-common-data';

/**
 * A flavor of a line item whereby customers purchase an item and pick it up from a location on a future date and time. SaleForPickup is currently not supported. 
 * @export
 * @interface SaleForPickupBase
 */
export interface SaleForPickupBase {
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof SaleForPickupBase
     */
    any?: Array<object>;
    /**
     * 
     * @type {Array<ItemID>}
     * @memberof SaleForPickupBase
     */
    ItemID?: Array<ItemID>;
    /**
     * 
     * @type {Array<MerchandiseHierarchyCommonData>}
     * @memberof SaleForPickupBase
     */
    MerchandiseHierarchy?: Array<MerchandiseHierarchyCommonData>;
    /**
     * 
     * @type {UnitPriceCommonData}
     * @memberof SaleForPickupBase
     */
    RegularSalesUnitPrice?: UnitPriceCommonData;
    /**
     * 
     * @type {ExtendedAmountType}
     * @memberof SaleForPickupBase
     */
    ExtendedAmount?: ExtendedAmountType;
    /**
     * 
     * @type {AmountCommonData}
     * @memberof SaleForPickupBase
     */
    ExtendedDiscountAmount?: AmountCommonData;
    /**
     * 
     * @type {Array<QuantityCommonData>}
     * @memberof SaleForPickupBase
     */
    Quantity?: Array<QuantityCommonData>;
    /**
     * 
     * @type {Array<RetailPriceModifierDomainSpecific>}
     * @memberof SaleForPickupBase
     */
    RetailPriceModifier?: Array<RetailPriceModifierDomainSpecific>;
    /**
     * 
     * @type {Array<ItemLink>}
     * @memberof SaleForPickupBase
     */
    ItemLink?: Array<ItemLink>;
    /**
     * 
     * @type {string}
     * @memberof SaleForPickupBase
     */
    ItemType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    NonDiscountableFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    FixedPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    TaxIncludedInPriceFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    NonPieceGoodFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    FrequentShopperPointsEligibilityFlag?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SaleForPickupBase
     */
    DiscountTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleForPickupBase
     */
    PriceTypeCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SaleForPickupBase
     */
    NotConsideredByPriceEngineFlag?: boolean;
    /**
     * 
     * @type {Array<FrequentShopperPointsModifierType>}
     * @memberof SaleForPickupBase
     */
    FrequentShopperPointsModifier?: Array<FrequentShopperPointsModifierType>;
    /**
     * 
     * @type {Array<PromotionPriceDerivationRuleReferenceType>}
     * @memberof SaleForPickupBase
     */
    PromotionPriceDerivationRuleReference?: Array<PromotionPriceDerivationRuleReferenceType>;
    /**
     * 
     * @type {Array<PromotionManualTriggerType>}
     * @memberof SaleForPickupBase
     */
    PromotionManualTrigger?: Array<PromotionManualTriggerType>;
}


