// tslint:disable
/**
* Calculation
* You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


import { LineItemDomainSpecific } from './line-item-domain-specific';

/**
 * The collection of the line items to be processed.
 * @export
 * @interface ShoppingBasketBase
 */
export interface ShoppingBasketBase {
    /**
     * The response might contain more line items than the request due to generated transaction discounts.
     * @type {Array<LineItemDomainSpecific>}
     * @memberof ShoppingBasketBase
     */
    LineItem: Array<LineItemDomainSpecific>;
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof ShoppingBasketBase
     */
    any?: Array<object>;
}


