// tslint:disable
/**
 * Calculation
 * You use the Calculation service for SAP Omnichannel Promotion Pricing in your sales channel application to determine the effective sales prices by applying promotional rules in the relevant customer context. The service can be called for a single product or for an entire shopping cart. The calculation is based on the data you uploaded to the cloud environment, and sends back prices and additional information about customer rewards to the calling application.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { QuantityCommonData } from './quantity-common-data';

/**
 * Allows the entry of coupons.
 * @export
 * @interface TenderCouponBase
 */
export interface TenderCouponBase {
    /**
     * 
     * @type {QuantityCommonData}
     * @memberof TenderCouponBase
     */
    Quantity?: QuantityCommonData;
    /**
     * Must be unique within this request.
     * @type {string}
     * @memberof TenderCouponBase
     */
    PrimaryLabel: string;
    /**
     * Reserved for future use.
     * @type {number}
     * @memberof TenderCouponBase
     */
    RewardValue?: number;
    /**
     * This is currently not supported.
     * @type {Array<object>}
     * @memberof TenderCouponBase
     */
    any?: Array<object>;
    /**
     * Quantity of items for which the provided coupons could be applied.
     * @type {number}
     * @memberof TenderCouponBase
     */
    AppliedQuantity?: number;
    /**
     * Reserved for future use.
     * @type {string}
     * @memberof TenderCouponBase
     */
    RewardType?: string;
}


