/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
/**
 * ExtensionApi - axios parameter creator
 * @export
 */
export declare const ExtensionApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    niceGetFunction: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    nicePostFunction: (options?: any) => Promise<RequestArgs>;
};
/**
 * ExtensionApi - functional programming interface
 * @export
 */
export declare const ExtensionApiFp: (configuration?: Configuration | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    niceGetFunction(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    nicePostFunction(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
};
/**
 * ExtensionApi - factory interface
 * @export
 */
export declare const ExtensionApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    niceGetFunction(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    nicePostFunction(options?: any): AxiosPromise<void>;
};
/**
 * ExtensionApi - object-oriented interface
 * @export
 * @class ExtensionApi
 * @extends {BaseAPI}
 */
export declare class ExtensionApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtensionApi
     */
    niceGetFunction(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtensionApi
     */
    nicePostFunction(options?: any): Promise<import("axios").AxiosResponse<void>>;
}
//# sourceMappingURL=extension-api.d.ts.map