/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
/**
 * TagSpaceApi - axios parameter creator
 * @export
 */
export declare const TagSpaceApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagWithSpace: (options?: any) => Promise<RequestArgs>;
};
/**
 * TagSpaceApi - functional programming interface
 * @export
 */
export declare const TagSpaceApiFp: (configuration?: Configuration | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagWithSpace(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
};
/**
 * TagSpaceApi - factory interface
 * @export
 */
export declare const TagSpaceApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagWithSpace(options?: any): AxiosPromise<void>;
};
/**
 * TagSpaceApi - object-oriented interface
 * @export
 * @class TagSpaceApi
 * @extends {BaseAPI}
 */
export declare class TagSpaceApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagSpaceApi
     */
    tagWithSpace(options?: any): Promise<import("axios").AxiosResponse<void>>;
}
//# sourceMappingURL=tag-space-api.d.ts.map