name: setup
description: Setup repo, node and pnpm.
inputs:
  node-version:
    description: 'Node.js version'
    default: '22'
  registry-url:
    description: 'The registry URL to use for npm packages'
    default: 'https://registry.npmjs.org'
  pnpm-version:
    description: 'PNPM version'
    default: '10'
  pnpm-install-args:
    description: 'Arguments to pass to pnpm install'
    default: '--frozen-lockfile'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'
    - run: pnpm install ${{ inputs.pnpm-install-args }}
      shell: bash
