/* Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. */

import { MethodRequestBuilderBase } from '../request-builder-base';

// FIXME: MethodRequestBuilderBase is too broad here. Should be create, update and delete
/**
 * Representation of a batch change set, which holds a collection of write operations.
 */
export interface BatchChangeSet<
  RequestT extends MethodRequestBuilderBase = any
> {
  /**
   * Requests to combine to one change set.
   */
  readonly requests: RequestT[];

  /**
   * Request boundary for separation of subrequests. Defaults to an autogenerated value.
   */
  readonly boundary: string;
}
