/* Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. */

import { v4 as uuid } from 'uuid';
import { MethodRequestBuilderBase } from '../request-builder-base';

// FIXME: MethodRequestBuilderBase is too broad here. Should be create, update and delete
/**
 * Representation of a batch change set, which holds a collection of write operations.
 */
export class BatchChangeSet<RequestT extends MethodRequestBuilderBase = any> {
  /**
   * Create an instance of BatchChangeSet.
   * @param requests Requests to combine to one change set.
   * @param boundary Request boundary for separation of subrequests. Defaults to an autogenerated value.
   */
  constructor(
    readonly requests: RequestT[],
    readonly boundary: string = `changeset_${uuid()}`
  ) {}
}

/**
 * Create a change set containing the given write requests.
 * @param requests Write requests to combine into one changeset.
 * @returns A change containing the given write requests.
 */
export function changeset<RequestT extends MethodRequestBuilderBase>(
  ...requests: RequestT[]
): BatchChangeSet<RequestT> {
  return new BatchChangeSet(requests);
}
