import { TestEntity50Col } from './TestEntity50Col';
import { TestEntity50ColRequestBuilder } from './TestEntity50ColRequestBuilder';
import { CustomField, DefaultDeSerializers, DeSerializers, AllFields, EntityBuilderType, EntityApi, FieldBuilder, OrderableEdmTypeField, EdmTypeField } from '@sap-cloud-sdk/odata-v4';
export declare class TestEntity50ColApi<DeSerializersT extends DeSerializers = DefaultDeSerializers> implements EntityApi<TestEntity50Col<DeSerializersT>, DeSerializersT> {
    deSerializers: DeSerializersT;
    constructor(deSerializers?: DeSerializersT);
    private navigationPropertyFields;
    _addNavigationProperties(linkedApis: [
    ]): this;
    entityConstructor: typeof TestEntity50Col;
    requestBuilder(): TestEntity50ColRequestBuilder<DeSerializersT>;
    entityBuilder(): EntityBuilderType<TestEntity50Col<DeSerializersT>, DeSerializersT>;
    customField<NullableT extends boolean = false>(fieldName: string, isNullable?: NullableT): CustomField<TestEntity50Col<DeSerializersT>, DeSerializersT, NullableT>;
    private _fieldBuilder?;
    get fieldBuilder(): FieldBuilder<typeof TestEntity50Col, DeSerializersT>;
    private _schema?;
    get schema(): {
        KEY_TEST_ENTITY_50_COL: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int32", false, true>;
        STRING_PROPERTY_1: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_1: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_1: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_1: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_2: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_2: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_2: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_2: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_3: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_3: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_3: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_3: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_4: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_4: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_4: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_4: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_5: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_5: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_5: EdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_5: OrderableEdmTypeField<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        ALL_FIELDS: AllFields<TestEntity50Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>>;
    };
}
//# sourceMappingURL=TestEntity50ColApi.d.ts.map