import { TestEntity100Col } from './TestEntity100Col';
import { TestEntity100ColRequestBuilder } from './TestEntity100ColRequestBuilder';
import { CustomField, DefaultDeSerializers, DeSerializers, AllFields, EntityBuilderType, EntityApi, FieldBuilder, OrderableEdmTypeField, EdmTypeField } from '@sap-cloud-sdk/odata-v4';
export declare class TestEntity100ColApi<DeSerializersT extends DeSerializers = DefaultDeSerializers> implements EntityApi<TestEntity100Col<DeSerializersT>, DeSerializersT> {
    deSerializers: DeSerializersT;
    constructor(deSerializers?: DeSerializersT);
    private navigationPropertyFields;
    _addNavigationProperties(linkedApis: [
    ]): this;
    entityConstructor: typeof TestEntity100Col;
    requestBuilder(): TestEntity100ColRequestBuilder<DeSerializersT>;
    entityBuilder(): EntityBuilderType<TestEntity100Col<DeSerializersT>, DeSerializersT>;
    customField<NullableT extends boolean = false>(fieldName: string, isNullable?: NullableT): CustomField<TestEntity100Col<DeSerializersT>, DeSerializersT, NullableT>;
    private _fieldBuilder?;
    get fieldBuilder(): FieldBuilder<typeof TestEntity100Col, DeSerializersT>;
    private _schema?;
    get schema(): {
        KEY_TEST_ENTITY_100_COL: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int32", false, true>;
        STRING_PROPERTY_1: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_1: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_1: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_1: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_2: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_2: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_2: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_2: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_3: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_3: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_3: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_3: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_4: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_4: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_4: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_4: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_5: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_5: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_5: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_5: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_11: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_11: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_11: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_11: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_12: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_12: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_12: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_12: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_13: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_13: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_13: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_13: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_14: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_14: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_14: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_14: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        STRING_PROPERTY_15: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.String", true, true>;
        GUID_PROPERTY_15: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Guid", true, true>;
        BOOLEAN_PROPERTY_15: EdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Boolean", true, true>;
        INT_64_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Int64", true, true>;
        DOUBLE_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Double", true, true>;
        DECIMAL_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Decimal", true, true>;
        DATE_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.Date", true, true>;
        TIME_OF_DAY_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.TimeOfDay", true, true>;
        DATA_TIME_OFFSET_DATA_TIME_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        DATA_TIME_OFFSET_TIMESTAMP_PROPERTY_15: OrderableEdmTypeField<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>, DeSerializersT, "Edm.DateTimeOffset", true, true>;
        ALL_FIELDS: AllFields<TestEntity100Col<DeSerializers<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>>>;
    };
}
//# sourceMappingURL=TestEntity100ColApi.d.ts.map