import { v4 as uuid } from 'uuid';
import { BatchSubRequestPathType } from '../request-builder/batch/batch-request-options';
import { ODataRequestConfig } from './odata-request-config';

/**
 * OData batch request configuration for an entity type.
 */
export class ODataBatchRequestConfig extends ODataRequestConfig {
  subRequestPathType: BatchSubRequestPathType = 'relativeToService';

  /**
   * Creates an instance of ODataBatchRequestConfig.
   * @param defaultServicePath - The default OData service path.
   * @param boundary - Request boundary for separation of subrequests. Defaults to an autogenerated value.
   */
  constructor(
    readonly defaultServicePath: string,
    readonly boundary = `batch_${uuid()}`
  ) {
    super('post', defaultServicePath, {
      'content-type': `multipart/mixed; boundary=${boundary}`,
      accept: 'multipart/mixed'
    });
  }

  withSubRequestPathType(subRequestPathType: BatchSubRequestPathType): void {
    this.subRequestPathType = subRequestPathType;
  }

  resourcePath(): string {
    return '$batch';
  }

  queryParameters(): Record<string, any> {
    return {};
  }
}
