import { randomUUID } from 'node:crypto';
import { ODataRequestConfig } from './odata-request-config';
import type { BatchSubRequestPathType } from '../request-builder';

/**
 * OData batch request configuration for an entity type.
 */
export class ODataBatchRequestConfig extends ODataRequestConfig {
  subRequestPathType: BatchSubRequestPathType = 'relativeToService';

  /**
   * Creates an instance of ODataBatchRequestConfig.
   * @param defaultBasePath - The default OData service path.
   * @param boundary - Request boundary for separation of subrequests. Defaults to an autogenerated value.
   */
  constructor(
    readonly defaultBasePath: string,
    readonly boundary = `batch_${randomUUID()}`
  ) {
    super('post', defaultBasePath, {
      'content-type': `multipart/mixed; boundary=${boundary}`,
      accept: 'multipart/mixed'
    });
  }

  withSubRequestPathType(subRequestPathType: BatchSubRequestPathType): void {
    this.subRequestPathType = subRequestPathType;
  }

  resourcePath(): string {
    return '$batch';
  }

  queryParameters(): Record<string, any> {
    return {};
  }
}
