/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleTestEntity } from './simple-test-entity';
/**
 * TestEntity schema
 * @export
 * @interface TestEntity
 */
export interface TestEntity {
    /**
     *
     * @type {string}
     * @memberof TestEntity
     */
    keyProperty: string;
    /**
     *
     * @type {string}
     * @memberof TestEntity
     */
    stringProperty?: string;
    /**
     *
     * @type {string}
     * @memberof TestEntity
     */
    dateProperty?: string;
    /**
     *
     * @type {string}
     * @memberof TestEntity
     */
    dateTimeProperty?: string;
    /**
     *
     * @type {number}
     * @memberof TestEntity
     */
    int32Property?: number;
    /**
     *
     * @type {number}
     * @memberof TestEntity
     */
    int64Property?: number;
    /**
     *
     * @type {number}
     * @memberof TestEntity
     */
    floatProperty?: number;
    /**
     *
     * @type {number}
     * @memberof TestEntity
     */
    doubleProperty?: number;
    /**
     *
     * @type {SimpleTestEntity}
     * @memberof TestEntity
     */
    linkedSimpleTestEntity?: SimpleTestEntity;
    /**
     *
     * @type {Array<SimpleTestEntity>}
     * @memberof TestEntity
     */
    linkedSimpleTestEntityCollection?: Array<SimpleTestEntity>;
}
//# sourceMappingURL=test-entity.d.ts.map