/**
 * Within all files generated by the SDK we use the unix style end of line delimiter.
 * We do not consider if the generator is executed on windows or unix systems.
 * It will always be `\n` to have consistent clients between operating systems.
 * @deprecated Since v4.6.0. Use '\n' directly instead.
 */
export const unixEOL = '\n';

/**
 * For request payloads, etc., it is convention to use the `\r\n` new line.
 * @deprecated Since v4.6.0. Use '\r\n' directly instead.
 */
export const webEOL = '\r\n';

type CharKind = 'upper' | 'lower' | 'digit' | 'separator';

// Uses Unicode property escapes to correctly classify non-ASCII letters and digits
// (e.g. accented uppercase Ü, Arabic-Indic digits ٣). Caseless letters (CJK, Arabic,
// titlecase like Dž) are treated as lowercase so they are included in words rather than dropped.
function charKind(c: string): CharKind {
  if (/^\p{Lu}$/u.test(c)) {
    return 'upper';
  }
  if (/^\p{L}$/u.test(c)) {
    return 'lower';
  } // covers Ll, Lt, Lm, Lo
  if (/^\p{N}$/u.test(c)) {
    return 'digit';
  }
  return 'separator';
}

// Splits an identifier string into words, handling common case conventions:
//   camelCase → ['camel', 'Case']
//   XMLParser → ['XML', 'Parser']
//   field_name → ['field', 'name']
//   Field13Name → ['Field', '13', 'Name']
function words(str: string): string[] {
  if (!str) {
    return [];
  }
  const result: string[] = [];
  let word = '';
  let state: CharKind | 'none' = 'none';

  const pushWord = () => {
    if (word) {
      result.push(word);
    }
    word = '';
  };

  for (const char of str) {
    const kind = charKind(char);

    if (state === 'none' || state === 'separator') {
      if (kind !== 'separator') {
        word = char;
        state = kind;
      }
    } else if (kind === 'separator') {
      pushWord();
      state = 'separator';
    } else if (kind === 'lower' && state === 'upper') {
      // Transition into a lowercase run: if we accumulated multiple uppers,
      // the last one belongs to this new word (e.g. XMLParser → XML + Parser)
      if (word.length > 1) {
        const last = word.slice(-1);
        word = word.slice(0, -1);
        pushWord();
        word = last;
      }
      word += char;
      state = 'lower';
    } else if (kind !== state) {
      // Any other kind change (lower→digit, digit→upper, etc.) starts a new word
      pushWord();
      word = char;
      state = kind;
    } else {
      word += char;
    }
  }

  pushWord();

  return result;
}

// Applies transforms to the first Unicode code point and the remainder.
// Uses codePointAt to correctly handle surrogate pairs (e.g. emoji, some CJK).
function transformInitialLetter(
  str: string,
  headTransform: (c: string) => string,
  tailTransform: (s: string) => string = s => s
): string {
  if (!str?.length) {
    return str ?? '';
  }
  // A surrogate pair occupies 2 UTF-16 code units; all BMP chars occupy 1.
  const firstCharLength = str.codePointAt(0)! > 0xffff ? 2 : 1;
  return (
    headTransform(str.slice(0, firstCharLength)) +
    tailTransform(str.slice(firstCharLength))
  );
}

/**
 * Uppercase the first character of a string, leaving the rest unchanged.
 * @param str - The string to capitalize.
 * @returns The string with the first character uppercased.
 */
export function capitalize(str: string): string {
  return transformInitialLetter(str, c => c.toUpperCase());
}

/**
 * Lowercase the first character of a string, leaving the rest unchanged.
 * @param str - The string to decapitalize.
 * @returns The string with the first character lowercased.
 * @internal
 */
export function decapitalize(str: string): string {
  return transformInitialLetter(str, c => c.toLowerCase());
}

function capitalizeWord(str: string): string {
  return transformInitialLetter(
    str,
    c => c.toUpperCase(),
    s => s.toLowerCase()
  );
}

/**
 * Convert a string to the uppercase snake case. This format is used e.g. for static properties on entity classes.
 * @param str - The string to be transformed.
 * @returns The input string in the case used by static methods on entity-classes.
 */
export function upperCaseSnakeCase(str: string): string {
  return words(str).join('_').toUpperCase();
}

/**
 * Convert a string to camelCase. This format used e.g. for properties on entity class instances.
 * @param str - The string to be transformed.
 * @returns The transformed string.
 */
export function camelCase(str: string): string {
  const parts = words(str);
  if (!parts.length) {
    return '';
  }
  return parts[0].toLowerCase() + parts.slice(1).map(capitalizeWord).join('');
}

/**
 * Convert a string to a human readable format, e.g. it transforms `to_BusinessPartner` to `To Business Partner`.
 * @param str - The string to be transformed.
 * @returns The transformed string.
 */
export function titleFormat(str: string): string {
  return words(str).map(capitalizeWord).join(' ');
}

/**
 * Convert a string to pascal case. This format is used e.g. for types.
 * @param str - The string to be transformed.
 * @returns The transformed string.
 */
export function pascalCase(str: string): string {
  return words(str).map(capitalize).join('');
}

/**
 * Convert a string to kebab case. This format is used e.g. for file names.
 * @param str - The string to be transformed.
 * @returns The transformed string.
 */
export function kebabCase(str: string): string {
  return words(str).join('-').toLowerCase();
}

/**
 * Uppercase the first character after each word boundary, leaving separators intact.
 * E.g. `content-type` → `Content-Type`, `if-match` → `If-Match`.
 * @param str - The string to transform.
 * @returns The string with each word's first character uppercased.
 */
export function titleCase(str: string): string {
  return str.replace(/\b\w/g, c => c.toUpperCase());
}

/**
 * Convert a JSON object to a string using formatting in line with the prettier with indentation and new line at the end.
 * @param json - Object to be stringified.
 * @returns The JSON object as string.
 */
export function formatJson(json: any): string {
  return JSON.stringify(json, null, 2) + '\n';
}
