"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Test Service
 * Test Service for OpenApi version 2 aka. Swagger as YAML file.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=test-entity.js.map