"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * Copyright (c) 2022 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
__exportStar(require("./AddressEmailAddress"), exports);
__exportStar(require("./AddressFaxNumber"), exports);
__exportStar(require("./AddressHomePageUrl"), exports);
__exportStar(require("./AddressPhoneNumber"), exports);
__exportStar(require("./BpContactToAddress"), exports);
__exportStar(require("./BpContactToFuncAndDept"), exports);
__exportStar(require("./BuPaAddressUsage"), exports);
__exportStar(require("./BuPaIdentification"), exports);
__exportStar(require("./BuPaIndustry"), exports);
__exportStar(require("./BusinessPartner"), exports);
__exportStar(require("./BusinessPartnerAddress"), exports);
__exportStar(require("./BusinessPartnerBank"), exports);
__exportStar(require("./BusinessPartnerContact"), exports);
__exportStar(require("./BusinessPartnerRole"), exports);
__exportStar(require("./BusinessPartnerTaxNumber"), exports);
__exportStar(require("./Customer"), exports);
__exportStar(require("./CustomerCompany"), exports);
__exportStar(require("./CustomerCompanyText"), exports);
__exportStar(require("./CustomerDunning"), exports);
__exportStar(require("./CustomerSalesArea"), exports);
__exportStar(require("./CustomerSalesAreaTax"), exports);
__exportStar(require("./CustomerSalesAreaText"), exports);
__exportStar(require("./CustomerTaxGrouping"), exports);
__exportStar(require("./CustomerText"), exports);
__exportStar(require("./CustomerUnloadingPoint"), exports);
__exportStar(require("./CustomerWithHoldingTax"), exports);
__exportStar(require("./CustSalesPartnerFunc"), exports);
__exportStar(require("./Supplier"), exports);
__exportStar(require("./SupplierCompany"), exports);
__exportStar(require("./SupplierCompanyText"), exports);
__exportStar(require("./SupplierDunning"), exports);
__exportStar(require("./SupplierPartnerFunc"), exports);
__exportStar(require("./SupplierPurchasingOrg"), exports);
__exportStar(require("./SupplierPurchasingOrgText"), exports);
__exportStar(require("./SupplierText"), exports);
__exportStar(require("./SupplierWithHoldingTax"), exports);
__exportStar(require("./AddressEmailAddressApi"), exports);
__exportStar(require("./AddressFaxNumberApi"), exports);
__exportStar(require("./AddressHomePageUrlApi"), exports);
__exportStar(require("./AddressPhoneNumberApi"), exports);
__exportStar(require("./BpContactToAddressApi"), exports);
__exportStar(require("./BpContactToFuncAndDeptApi"), exports);
__exportStar(require("./BuPaAddressUsageApi"), exports);
__exportStar(require("./BuPaIdentificationApi"), exports);
__exportStar(require("./BuPaIndustryApi"), exports);
__exportStar(require("./BusinessPartnerApi"), exports);
__exportStar(require("./BusinessPartnerAddressApi"), exports);
__exportStar(require("./BusinessPartnerBankApi"), exports);
__exportStar(require("./BusinessPartnerContactApi"), exports);
__exportStar(require("./BusinessPartnerRoleApi"), exports);
__exportStar(require("./BusinessPartnerTaxNumberApi"), exports);
__exportStar(require("./CustomerApi"), exports);
__exportStar(require("./CustomerCompanyApi"), exports);
__exportStar(require("./CustomerCompanyTextApi"), exports);
__exportStar(require("./CustomerDunningApi"), exports);
__exportStar(require("./CustomerSalesAreaApi"), exports);
__exportStar(require("./CustomerSalesAreaTaxApi"), exports);
__exportStar(require("./CustomerSalesAreaTextApi"), exports);
__exportStar(require("./CustomerTaxGroupingApi"), exports);
__exportStar(require("./CustomerTextApi"), exports);
__exportStar(require("./CustomerUnloadingPointApi"), exports);
__exportStar(require("./CustomerWithHoldingTaxApi"), exports);
__exportStar(require("./CustSalesPartnerFuncApi"), exports);
__exportStar(require("./SupplierApi"), exports);
__exportStar(require("./SupplierCompanyApi"), exports);
__exportStar(require("./SupplierCompanyTextApi"), exports);
__exportStar(require("./SupplierDunningApi"), exports);
__exportStar(require("./SupplierPartnerFuncApi"), exports);
__exportStar(require("./SupplierPurchasingOrgApi"), exports);
__exportStar(require("./SupplierPurchasingOrgTextApi"), exports);
__exportStar(require("./SupplierTextApi"), exports);
__exportStar(require("./SupplierWithHoldingTaxApi"), exports);
__exportStar(require("./AddressEmailAddressRequestBuilder"), exports);
__exportStar(require("./AddressFaxNumberRequestBuilder"), exports);
__exportStar(require("./AddressHomePageUrlRequestBuilder"), exports);
__exportStar(require("./AddressPhoneNumberRequestBuilder"), exports);
__exportStar(require("./BpContactToAddressRequestBuilder"), exports);
__exportStar(require("./BpContactToFuncAndDeptRequestBuilder"), exports);
__exportStar(require("./BuPaAddressUsageRequestBuilder"), exports);
__exportStar(require("./BuPaIdentificationRequestBuilder"), exports);
__exportStar(require("./BuPaIndustryRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerAddressRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerBankRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerContactRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerRoleRequestBuilder"), exports);
__exportStar(require("./BusinessPartnerTaxNumberRequestBuilder"), exports);
__exportStar(require("./CustomerRequestBuilder"), exports);
__exportStar(require("./CustomerCompanyRequestBuilder"), exports);
__exportStar(require("./CustomerCompanyTextRequestBuilder"), exports);
__exportStar(require("./CustomerDunningRequestBuilder"), exports);
__exportStar(require("./CustomerSalesAreaRequestBuilder"), exports);
__exportStar(require("./CustomerSalesAreaTaxRequestBuilder"), exports);
__exportStar(require("./CustomerSalesAreaTextRequestBuilder"), exports);
__exportStar(require("./CustomerTaxGroupingRequestBuilder"), exports);
__exportStar(require("./CustomerTextRequestBuilder"), exports);
__exportStar(require("./CustomerUnloadingPointRequestBuilder"), exports);
__exportStar(require("./CustomerWithHoldingTaxRequestBuilder"), exports);
__exportStar(require("./CustSalesPartnerFuncRequestBuilder"), exports);
__exportStar(require("./SupplierRequestBuilder"), exports);
__exportStar(require("./SupplierCompanyRequestBuilder"), exports);
__exportStar(require("./SupplierCompanyTextRequestBuilder"), exports);
__exportStar(require("./SupplierDunningRequestBuilder"), exports);
__exportStar(require("./SupplierPartnerFuncRequestBuilder"), exports);
__exportStar(require("./SupplierPurchasingOrgRequestBuilder"), exports);
__exportStar(require("./SupplierPurchasingOrgTextRequestBuilder"), exports);
__exportStar(require("./SupplierTextRequestBuilder"), exports);
__exportStar(require("./SupplierWithHoldingTaxRequestBuilder"), exports);
__exportStar(require("./BatchRequest"), exports);
__exportStar(require("./service"), exports);
//# sourceMappingURL=index.js.map