/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (
  configuration?: Configuration | undefined
) => {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  defaultTag: (options?: any) => Promise<RequestArgs>;
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  noTag: (options?: any) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (
  configuration?: Configuration | undefined
) => {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  defaultTag(
    options?: any
  ): Promise<
    (
      axios?: AxiosInstance | undefined,
      basePath?: string | undefined
    ) => AxiosPromise<void>
  >;
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  noTag(
    options?: any
  ): Promise<
    (
      axios?: AxiosInstance | undefined,
      basePath?: string | undefined
    ) => AxiosPromise<void>
  >;
};
/**
 * DefaultApi - factory interface
 * @export
 */
export declare const DefaultApiFactory: (
  configuration?: Configuration | undefined,
  basePath?: string | undefined,
  axios?: AxiosInstance | undefined
) => {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  defaultTag(options?: any): AxiosPromise<void>;
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  noTag(options?: any): AxiosPromise<void>;
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  defaultTag(options?: any): Promise<import('axios').AxiosResponse<void>>;
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  noTag(options?: any): Promise<import('axios').AxiosResponse<void>>;
}
//# sourceMappingURL=default-api.d.ts.map
