/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { SimpleTestEntity } from '../model';
import { TestEntity } from '../model';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     * Count entities
     * @summary Count entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    countEntities: (options?: any) => Promise<RequestArgs>;
    /**
     * Create entity
     * @summary Create entity
     * @param {TestEntity} [testEntity] Entity to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createEntity: (testEntity?: TestEntity | undefined, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {Array<string>} [requestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteEntity: (requestBody?: string[] | undefined, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId1: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId2: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId3: (options?: any) => Promise<RequestArgs>;
    /**
     * Get all entities
     * @summary Get entities
     * @param {string} [stringParameter] A parameter of type string
     * @param {number} [integerParameter] A parameter of type integer
     * @param {string} [$dollarParameter] A parameter that contains $
     * @param {string} [dotParameter] A parameter that contains . in the middle
     * @param {'value1' | 'value2'} [enumStringParameter] A parameter of type enum with string
     * @param {1 | 2} [enumInt32Parameter] A parameter of type enum with int 32
     * @param {1 | 2} [enumDoubleParameter] A parameter of type enum with double
     * @param {boolean} [enumBooleanParameter] A parameter of type enum with boolean
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllEntities: (stringParameter?: string | undefined, integerParameter?: number | undefined, $dollarParameter?: string | undefined, dotParameter?: string | undefined, enumStringParameter?: "value1" | "value2" | undefined, enumInt32Parameter?: 1 | 2 | undefined, enumDoubleParameter?: 1 | 2 | undefined, enumBooleanParameter?: boolean | undefined, options?: any) => Promise<RequestArgs>;
    /**
     * Get entity by id
     * @summary Get entity by id
     * @param {string} entityId Key property of the entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEntityByKey: (entityId: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTestCasesNoOperationId: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {string} duplicateParam
     * @param {string} duplicateParam2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetDuplicateParameters: (duplicateParam: string, duplicateParam2: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {string} [optionalQueryParam]
     * @param {string} [optionalPathItemQueryParam] Overrides original path item query parameter.
     * @param {SimpleTestEntity} [simpleTestEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetRequiredParameters: (requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, optionalQueryParam?: string | undefined, optionalPathItemQueryParam?: string | undefined, simpleTestEntity?: SimpleTestEntity | undefined, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {SimpleTestEntity} simpleTestEntity
     * @param {string} [optionalPathItemQueryParam]
     * @param {string} [optionalQueryParam]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePostRequiredParameters: (requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, simpleTestEntity: SimpleTestEntity, optionalPathItemQueryParam?: string | undefined, optionalQueryParam?: string | undefined, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {object} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntity: (body?: object | undefined, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {Array<TestEntity>} [testEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntityWithPut: (testEntity?: TestEntity[] | undefined, options?: any) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (configuration?: Configuration | undefined) => {
    /**
     * Count entities
     * @summary Count entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    countEntities(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<number>>;
    /**
     * Create entity
     * @summary Create entity
     * @param {TestEntity} [testEntity] Entity to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createEntity(testEntity?: TestEntity | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {Array<string>} [requestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteEntity(requestBody?: string[] | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId1(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId2(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId3(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     * Get all entities
     * @summary Get entities
     * @param {string} [stringParameter] A parameter of type string
     * @param {number} [integerParameter] A parameter of type integer
     * @param {string} [$dollarParameter] A parameter that contains $
     * @param {string} [dotParameter] A parameter that contains . in the middle
     * @param {'value1' | 'value2'} [enumStringParameter] A parameter of type enum with string
     * @param {1 | 2} [enumInt32Parameter] A parameter of type enum with int 32
     * @param {1 | 2} [enumDoubleParameter] A parameter of type enum with double
     * @param {boolean} [enumBooleanParameter] A parameter of type enum with boolean
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllEntities(stringParameter?: string | undefined, integerParameter?: number | undefined, $dollarParameter?: string | undefined, dotParameter?: string | undefined, enumStringParameter?: "value1" | "value2" | undefined, enumInt32Parameter?: 1 | 2 | undefined, enumDoubleParameter?: 1 | 2 | undefined, enumBooleanParameter?: boolean | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<Array<TestEntity>>>;
    /**
     * Get entity by id
     * @summary Get entity by id
     * @param {string} entityId Key property of the entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEntityByKey(entityId: string, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<Array<TestEntity>>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTestCasesNoOperationId(options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {string} duplicateParam
     * @param {string} duplicateParam2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetDuplicateParameters(duplicateParam: string, duplicateParam2: string, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {string} [optionalQueryParam]
     * @param {string} [optionalPathItemQueryParam] Overrides original path item query parameter.
     * @param {SimpleTestEntity} [simpleTestEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, optionalQueryParam?: string | undefined, optionalPathItemQueryParam?: string | undefined, simpleTestEntity?: SimpleTestEntity | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {SimpleTestEntity} simpleTestEntity
     * @param {string} [optionalPathItemQueryParam]
     * @param {string} [optionalQueryParam]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePostRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, simpleTestEntity: SimpleTestEntity, optionalPathItemQueryParam?: string | undefined, optionalQueryParam?: string | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {object} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntity(body?: object | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
    /**
     *
     * @param {Array<TestEntity>} [testEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntityWithPut(testEntity?: TestEntity[] | undefined, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>>;
};
/**
 * DefaultApi - factory interface
 * @export
 */
export declare const DefaultApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     * Count entities
     * @summary Count entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    countEntities(options?: any): AxiosPromise<number>;
    /**
     * Create entity
     * @summary Create entity
     * @param {TestEntity} [testEntity] Entity to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createEntity(testEntity?: TestEntity | undefined, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {Array<string>} [requestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteEntity(requestBody?: string[] | undefined, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId1(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId2(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    duplicateOperationId3(options?: any): AxiosPromise<void>;
    /**
     * Get all entities
     * @summary Get entities
     * @param {string} [stringParameter] A parameter of type string
     * @param {number} [integerParameter] A parameter of type integer
     * @param {string} [$dollarParameter] A parameter that contains $
     * @param {string} [dotParameter] A parameter that contains . in the middle
     * @param {'value1' | 'value2'} [enumStringParameter] A parameter of type enum with string
     * @param {1 | 2} [enumInt32Parameter] A parameter of type enum with int 32
     * @param {1 | 2} [enumDoubleParameter] A parameter of type enum with double
     * @param {boolean} [enumBooleanParameter] A parameter of type enum with boolean
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllEntities(stringParameter?: string | undefined, integerParameter?: number | undefined, $dollarParameter?: string | undefined, dotParameter?: string | undefined, enumStringParameter?: "value1" | "value2" | undefined, enumInt32Parameter?: 1 | 2 | undefined, enumDoubleParameter?: 1 | 2 | undefined, enumBooleanParameter?: boolean | undefined, options?: any): AxiosPromise<Array<TestEntity>>;
    /**
     * Get entity by id
     * @summary Get entity by id
     * @param {string} entityId Key property of the entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEntityByKey(entityId: string, options?: any): AxiosPromise<Array<TestEntity>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTestCasesNoOperationId(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {string} duplicateParam
     * @param {string} duplicateParam2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetDuplicateParameters(duplicateParam: string, duplicateParam2: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {string} [optionalQueryParam]
     * @param {string} [optionalPathItemQueryParam] Overrides original path item query parameter.
     * @param {SimpleTestEntity} [simpleTestEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGetRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, optionalQueryParam?: string | undefined, optionalPathItemQueryParam?: string | undefined, simpleTestEntity?: SimpleTestEntity | undefined, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {SimpleTestEntity} simpleTestEntity
     * @param {string} [optionalPathItemQueryParam]
     * @param {string} [optionalQueryParam]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePostRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, simpleTestEntity: SimpleTestEntity, optionalPathItemQueryParam?: string | undefined, optionalQueryParam?: string | undefined, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {object} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntity(body?: object | undefined, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {Array<TestEntity>} [testEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEntityWithPut(testEntity?: TestEntity[] | undefined, options?: any): AxiosPromise<void>;
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI {
    /**
     * Count entities
     * @summary Count entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    countEntities(options?: any): Promise<import("axios").AxiosResponse<number>>;
    /**
     * Create entity
     * @summary Create entity
     * @param {TestEntity} [testEntity] Entity to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createEntity(testEntity?: TestEntity, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {Array<string>} [requestBody]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    deleteEntity(requestBody?: Array<string>, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    duplicateOperationId(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    duplicateOperationId1(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    duplicateOperationId2(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    duplicateOperationId3(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     * Get all entities
     * @summary Get entities
     * @param {string} [stringParameter] A parameter of type string
     * @param {number} [integerParameter] A parameter of type integer
     * @param {string} [$dollarParameter] A parameter that contains $
     * @param {string} [dotParameter] A parameter that contains . in the middle
     * @param {'value1' | 'value2'} [enumStringParameter] A parameter of type enum with string
     * @param {1 | 2} [enumInt32Parameter] A parameter of type enum with int 32
     * @param {1 | 2} [enumDoubleParameter] A parameter of type enum with double
     * @param {boolean} [enumBooleanParameter] A parameter of type enum with boolean
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getAllEntities(stringParameter?: string, integerParameter?: number, $dollarParameter?: string, dotParameter?: string, enumStringParameter?: 'value1' | 'value2', enumInt32Parameter?: 1 | 2, enumDoubleParameter?: 1 | 2, enumBooleanParameter?: boolean, options?: any): Promise<import("axios").AxiosResponse<TestEntity[]>>;
    /**
     * Get entity by id
     * @summary Get entity by id
     * @param {string} entityId Key property of the entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getEntityByKey(entityId: string, options?: any): Promise<import("axios").AxiosResponse<TestEntity[]>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getTestCasesNoOperationId(options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {string} duplicateParam
     * @param {string} duplicateParam2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    testCaseGetDuplicateParameters(duplicateParam: string, duplicateParam2: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {string} [optionalQueryParam]
     * @param {string} [optionalPathItemQueryParam] Overrides original path item query parameter.
     * @param {SimpleTestEntity} [simpleTestEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    testCaseGetRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, optionalQueryParam?: string, optionalPathItemQueryParam?: string, simpleTestEntity?: SimpleTestEntity, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {string} requiredPathItemQueryParam
     * @param {string} requiredPathItemPathParam
     * @param {string} requiredQueryParam
     * @param {SimpleTestEntity} simpleTestEntity
     * @param {string} [optionalPathItemQueryParam]
     * @param {string} [optionalQueryParam]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    testCasePostRequiredParameters(requiredPathItemQueryParam: string, requiredPathItemPathParam: string, requiredQueryParam: string, simpleTestEntity: SimpleTestEntity, optionalPathItemQueryParam?: string, optionalQueryParam?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {object} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    updateEntity(body?: object, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @param {Array<TestEntity>} [testEntity]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    updateEntityWithPut(testEntity?: Array<TestEntity>, options?: any): Promise<import("axios").AxiosResponse<void>>;
}
//# sourceMappingURL=default-api.d.ts.map