import { v4 as uuid } from 'uuid';
import {
  BatchRequestOptions,
  defaultOptions
} from '../request-builder/batch/batch-request-options';
import { ODataRequestConfig } from './odata-request-config';

export class ODataBatchRequestConfig extends ODataRequestConfig {
  /**
   * @deprecated Since v1.30.0.
   */
  static readonly content_type_prefix = 'multipart/mixed; boundary=batch_';

  options: BatchRequestOptions = defaultOptions;

  /**
   * @deprecated Since v1.30.0. Use [[boundary]] instead.
   */
  get batchId() {
    return this.boundary;
  }

  /**
   * Creates an instance of ODataBatchRequestConfig.
   *
   * @param defaultServicePath The default OData service path
   * @param boundary Request boundary for separation of subrequests. Defaults to an autogenerated value.
   */
  constructor(
    readonly defaultServicePath: string,
    readonly boundary = `batch_${uuid()}`
  ) {
    super('post', defaultServicePath, {
      'content-type': `multipart/mixed; boundary=${boundary}`,
      accept: 'multipart/mixed'
    });
  }

  withOptions(options: BatchRequestOptions) {
    this.options = { ...this.options, ...options };
  }

  resourcePath(): string {
    return '$batch';
  }

  queryParameters(): Record<string, any> {
    return {};
  }
}
