name: 'commit-and-tag'
description: 'Commits and tags the current changes.'
inputs:
  version:
    description: 'Version to use for the tag and commit message'
runs:
  using: 'composite'
  steps:
    - run: |
        git add -A
        git commit -m "v$VERSION"
        git tag "v$VERSION"
        git push --follow-tags
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
