namespace cloudsdk.test;

entity TestEntityLink{
  key KeyTestEntityLink: Integer;
  key KeyToTestEntity: Integer;
  StringProperty: String(111);
}

entity TestEntity {
  key KeyTestEntity: Integer;
  StringProperty: String(111);
  GuidProperty: UUID;
  BooleanProperty: Boolean;
  Int64Property: Integer64;
  DoubleProperty: Double;
  DecimalProperty: Decimal(9,2);
  DateProperty: Date;
  TimeOfDayProperty: Time;
  DataTimeOffsetDataTimeProperty: DateTime;
  DataTimeOffsetTimestampProperty: Timestamp;
  //Only Composition allow for deep create. Associations do not. The reason is that Composition are self-contained.
  //So a child entity can not exist without a parent.
  ToMultiLink: Composition of many TestEntityLink on KeyTestEntity=ToMultiLink.KeyToTestEntity;
};

entity TestEntity50Col {
  key KeyTestEntity50Col: Integer;
  StringProperty1: String(111);
  GuidProperty1: UUID;
  BooleanProperty1: Boolean;
  Int64Property1: Integer64;
  DoubleProperty1: Double;
  DecimalProperty1: Decimal(9,2);
  DateProperty1: Date;
  TimeOfDayProperty1: Time;
  DataTimeOffsetDataTimeProperty1: DateTime;
  DataTimeOffsetTimestampProperty1: Timestamp;
  StringProperty2: String(111);
  GuidProperty2: UUID;
  BooleanProperty2: Boolean;
  Int64Property2: Integer64;
  DoubleProperty2: Double;
  DecimalProperty2: Decimal(9,2);
  DateProperty2: Date;
  TimeOfDayProperty2: Time;
  DataTimeOffsetDataTimeProperty2: DateTime;
  DataTimeOffsetTimestampProperty2: Timestamp;
  StringProperty3: String(111);
  GuidProperty3: UUID;
  BooleanProperty3: Boolean;
  Int64Property3: Integer64;
  DoubleProperty3: Double;
  DecimalProperty3: Decimal(9,2);
  DateProperty3: Date;
  TimeOfDayProperty3: Time;
  DataTimeOffsetDataTimeProperty3: DateTime;
  DataTimeOffsetTimestampProperty3: Timestamp;
  StringProperty4: String(111);
  GuidProperty4: UUID;
  BooleanProperty4: Boolean;
  Int64Property4: Integer64;
  DoubleProperty4: Double;
  DecimalProperty4: Decimal(9,2);
  DateProperty4: Date;
  TimeOfDayProperty4: Time;
  DataTimeOffsetDataTimeProperty4: DateTime;
  DataTimeOffsetTimestampProperty4: Timestamp;
  StringProperty5: String(111);
  GuidProperty5: UUID;
  BooleanProperty5: Boolean;
  Int64Property5: Integer64;
  DoubleProperty5: Double;
  DecimalProperty5: Decimal(9,2);
  DateProperty5: Date;
  TimeOfDayProperty5: Time;
  DataTimeOffsetDataTimeProperty5: DateTime;
  DataTimeOffsetTimestampProperty5: Timestamp;
}

entity TestEntity100Col {
  key KeyTestEntity100Col: Integer;
  StringProperty1: String(111);
  GuidProperty1: UUID;
  BooleanProperty1: Boolean;
  Int64Property1: Integer64;
  DoubleProperty1: Double;
  DecimalProperty1: Decimal(9,2);
  DateProperty1: Date;
  TimeOfDayProperty1: Time;
  DataTimeOffsetDataTimeProperty1: DateTime;
  DataTimeOffsetTimestampProperty1: Timestamp;
  StringProperty2: String(111);
  GuidProperty2: UUID;
  BooleanProperty2: Boolean;
  Int64Property2: Integer64;
  DoubleProperty2: Double;
  DecimalProperty2: Decimal(9,2);
  DateProperty2: Date;
  TimeOfDayProperty2: Time;
  DataTimeOffsetDataTimeProperty2: DateTime;
  DataTimeOffsetTimestampProperty2: Timestamp;
  StringProperty3: String(111);
  GuidProperty3: UUID;
  BooleanProperty3: Boolean;
  Int64Property3: Integer64;
  DoubleProperty3: Double;
  DecimalProperty3: Decimal(9,2);
  DateProperty3: Date;
  TimeOfDayProperty3: Time;
  DataTimeOffsetDataTimeProperty3: DateTime;
  DataTimeOffsetTimestampProperty3: Timestamp;
  StringProperty4: String(111);
  GuidProperty4: UUID;
  BooleanProperty4: Boolean;
  Int64Property4: Integer64;
  DoubleProperty4: Double;
  DecimalProperty4: Decimal(9,2);
  DateProperty4: Date;
  TimeOfDayProperty4: Time;
  DataTimeOffsetDataTimeProperty4: DateTime;
  DataTimeOffsetTimestampProperty4: Timestamp;
  StringProperty5: String(111);
  GuidProperty5: UUID;
  BooleanProperty5: Boolean;
  Int64Property5: Integer64;
  DoubleProperty5: Double;
  DecimalProperty5: Decimal(9,2);
  DateProperty5: Date;
  TimeOfDayProperty5: Time;
  DataTimeOffsetDataTimeProperty5: DateTime;
  DataTimeOffsetTimestampProperty5: Timestamp;
  StringProperty11: String(111);
  GuidProperty11: UUID;
  BooleanProperty11: Boolean;
  Int64Property11: Integer64;
  DoubleProperty11: Double;
  DecimalProperty11: Decimal(9,2);
  DateProperty11: Date;
  TimeOfDayProperty11: Time;
  DataTimeOffsetDataTimeProperty11: DateTime;
  DataTimeOffsetTimestampProperty11: Timestamp;
  StringProperty12: String(111);
  GuidProperty12: UUID;
  BooleanProperty12: Boolean;
  Int64Property12: Integer64;
  DoubleProperty12: Double;
  DecimalProperty12: Decimal(9,2);
  DateProperty12: Date;
  TimeOfDayProperty12: Time;
  DataTimeOffsetDataTimeProperty12: DateTime;
  DataTimeOffsetTimestampProperty12: Timestamp;
  StringProperty13: String(111);
  GuidProperty13: UUID;
  BooleanProperty13: Boolean;
  Int64Property13: Integer64;
  DoubleProperty13: Double;
  DecimalProperty13: Decimal(9,2);
  DateProperty13: Date;
  TimeOfDayProperty13: Time;
  DataTimeOffsetDataTimeProperty13: DateTime;
  DataTimeOffsetTimestampProperty13: Timestamp;
  StringProperty14: String(111);
  GuidProperty14: UUID;
  BooleanProperty14: Boolean;
  Int64Property14: Integer64;
  DoubleProperty14: Double;
  DecimalProperty14: Decimal(9,2);
  DateProperty14: Date;
  TimeOfDayProperty14: Time;
  DataTimeOffsetDataTimeProperty14: DateTime;
  DataTimeOffsetTimestampProperty14: Timestamp;
  StringProperty15: String(111);
  GuidProperty15: UUID;
  BooleanProperty15: Boolean;
  Int64Property15: Integer64;
  DoubleProperty15: Double;
  DecimalProperty15: Decimal(9,2);
  DateProperty15: Date;
  TimeOfDayProperty15: Time;
  DataTimeOffsetDataTimeProperty15: DateTime;
  DataTimeOffsetTimestampProperty15: Timestamp;
}


