name: 'Get current changelog'
description: 'Gets the current changelog'
outputs:
  changelog:
    description: 'The current changelog'
runs:
  using: 'node16'
  main: 'dist/.github/actions/get-changelog/index.js'
