"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SAPCPWorkflowCFApi = void 0;
/*
 * Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
var core_1 = require("@sap-cloud-sdk/core");
var api_1 = require("./openapi/api");
exports.SAPCPWorkflowCFApi = {
    getV1TaskInstances: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstances', args === null || args === void 0 ? void 0 : args.skip, args === null || args === void 0 ? void 0 : args.top, args === null || args === void 0 ? void 0 : args.inlinecount, args === null || args === void 0 ? void 0 : args.expand, args === null || args === void 0 ? void 0 : args.orderby, args === null || args === void 0 ? void 0 : args.workflowInstanceId, args === null || args === void 0 ? void 0 : args.workflowDefinitionId, args === null || args === void 0 ? void 0 : args.processor, args === null || args === void 0 ? void 0 : args.id, args === null || args === void 0 ? void 0 : args.activityId, args === null || args === void 0 ? void 0 : args.description, args === null || args === void 0 ? void 0 : args.subject, args === null || args === void 0 ? void 0 : args.createdAt, args === null || args === void 0 ? void 0 : args.createdFrom, args === null || args === void 0 ? void 0 : args.createdUpTo, args === null || args === void 0 ? void 0 : args.claimedAt, args === null || args === void 0 ? void 0 : args.claimedFrom, args === null || args === void 0 ? void 0 : args.claimedUpTo, args === null || args === void 0 ? void 0 : args.completedAt, args === null || args === void 0 ? void 0 : args.completedFrom, args === null || args === void 0 ? void 0 : args.completedUpTo, args === null || args === void 0 ? void 0 : args.lastChangedAt, args === null || args === void 0 ? void 0 : args.lastChangedFrom, args === null || args === void 0 ? void 0 : args.lastChangedUpTo, args === null || args === void 0 ? void 0 : args.dueDate, args === null || args === void 0 ? void 0 : args.dueDateFrom, args === null || args === void 0 ? void 0 : args.dueDateUpTo, args === null || args === void 0 ? void 0 : args.priority, args === null || args === void 0 ? void 0 : args.status, args === null || args === void 0 ? void 0 : args.recipientUsers, args === null || args === void 0 ? void 0 : args.recipientGroups, args === null || args === void 0 ? void 0 : args.containsText, args === null || args === void 0 ? void 0 : args.attributesExampleCustomAttribute, args === null || args === void 0 ? void 0 : args.definitionId); },
    getV1TaskInstancesByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesByTaskInstanceId', args.taskInstanceId, args.expand); },
    updateV1TaskInstancesByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1TaskInstancesByTaskInstanceId', args.taskInstanceId, args.body); },
    getV1TaskInstancesAttributesByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesAttributesByTaskInstanceId', args.taskInstanceId); },
    getV1TaskInstancesContextByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesContextByTaskInstanceId', args.taskInstanceId); },
    getV1TaskInstancesAttachmentsByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesAttachmentsByTaskInstanceId', args.taskInstanceId); },
    getV1TaskInstancesFormByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesFormByTaskInstanceId', args.taskInstanceId); },
    getV1TaskInstancesFormModelByTaskInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskInstancesFormModelByTaskInstanceId', args.taskInstanceId); },
    getV1TaskDefinitions: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1TaskDefinitions', args === null || args === void 0 ? void 0 : args.skip, args === null || args === void 0 ? void 0 : args.top, args === null || args === void 0 ? void 0 : args.inlinecount, args === null || args === void 0 ? void 0 : args.expand); },
    getV1WorkflowDefinitions: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitions', args === null || args === void 0 ? void 0 : args.orderby, args === null || args === void 0 ? void 0 : args.skip, args === null || args === void 0 ? void 0 : args.top, args === null || args === void 0 ? void 0 : args.inlinecount); },
    getV1WorkflowDefinitionsByDefinitionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsByDefinitionId', args.definitionId); },
    deleteV1WorkflowDefinitionsByDefinitionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'deleteV1WorkflowDefinitionsByDefinitionId', args.definitionId, args.cascade); },
    getV1WorkflowDefinitionsVersionsByDefinitionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsVersionsByDefinitionId', args.definitionId, args.orderby, args.skip, args.top, args.inlinecount); },
    getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber', args.definitionId, args.versionNumber); },
    getV1WorkflowDefinitionsModelByDefinitionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsModelByDefinitionId', args.definitionId); },
    getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber', args.definitionId, args.versionNumber); },
    getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId', args.definitionId); },
    getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber', args.definitionId, args.versionNumber); },
    getV1WorkflowInstances: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstances', args === null || args === void 0 ? void 0 : args.orderby, args === null || args === void 0 ? void 0 : args.skip, args === null || args === void 0 ? void 0 : args.top, args === null || args === void 0 ? void 0 : args.inlinecount, args === null || args === void 0 ? void 0 : args.expand, args === null || args === void 0 ? void 0 : args.id, args === null || args === void 0 ? void 0 : args.definitionId, args === null || args === void 0 ? void 0 : args.definitionVersion, args === null || args === void 0 ? void 0 : args.status, args === null || args === void 0 ? void 0 : args.startedAt, args === null || args === void 0 ? void 0 : args.startedFrom, args === null || args === void 0 ? void 0 : args.startedUpTo, args === null || args === void 0 ? void 0 : args.completedAt, args === null || args === void 0 ? void 0 : args.completedFrom, args === null || args === void 0 ? void 0 : args.completedUpTo, args === null || args === void 0 ? void 0 : args.startedBy, args === null || args === void 0 ? void 0 : args.subject, args === null || args === void 0 ? void 0 : args.containsText, args === null || args === void 0 ? void 0 : args.businessKey, args === null || args === void 0 ? void 0 : args.rootInstanceId, args === null || args === void 0 ? void 0 : args.parentInstanceId, args === null || args === void 0 ? void 0 : args.attributesExampleCustomAttribute); },
    createV1WorkflowInstances: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'createV1WorkflowInstances', args.body); },
    updateV1WorkflowInstances: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstances', args.body); },
    getV1WorkflowInstancesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesByWorkflowInstanceId', args.workflowInstanceId, args.expand); },
    updateV1WorkflowInstancesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstancesByWorkflowInstanceId', args.workflowInstanceId, args.body); },
    getV1WorkflowInstancesAttributesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesAttributesByWorkflowInstanceId', args.workflowInstanceId); },
    getV1WorkflowInstancesContextByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesContextByWorkflowInstanceId', args.workflowInstanceId); },
    updateV1WorkflowInstancesContextByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstancesContextByWorkflowInstanceId', args.workflowInstanceId, args.body); },
    updateV1WorkflowInstancesContextByWorkflowInstanceId1: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstancesContextByWorkflowInstanceId1', args.workflowInstanceId, args.body); },
    getV1WorkflowInstancesAttachmentsByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesAttachmentsByWorkflowInstanceId', args.workflowInstanceId); },
    updateV1WorkflowInstancesAttachmentsByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstancesAttachmentsByWorkflowInstanceId', args.workflowInstanceId, args.body); },
    getV1WorkflowInstancesErrorMessagesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesErrorMessagesByWorkflowInstanceId', args.workflowInstanceId); },
    getV1WorkflowInstancesExecutionLogsByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesExecutionLogsByWorkflowInstanceId', args.workflowInstanceId); },
    getV1WorkflowInstancesRolesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1WorkflowInstancesRolesByWorkflowInstanceId', args.workflowInstanceId); },
    updateV1WorkflowInstancesRolesByWorkflowInstanceId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'updateV1WorkflowInstancesRolesByWorkflowInstanceId', args.workflowInstanceId, args.body); },
    getV1Forms: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1Forms', args === null || args === void 0 ? void 0 : args.skip, args === null || args === void 0 ? void 0 : args.top, args === null || args === void 0 ? void 0 : args.inlinecount, args === null || args === void 0 ? void 0 : args.type); },
    deleteV1FormsByFormId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'deleteV1FormsByFormId', args.formId); },
    getV1FormsRevisionsModelByFormIdAndRevisionId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1FormsRevisionsModelByFormIdAndRevisionId', args.formId, args.revisionId); },
    getV1FormsVersionsModelByFormIdAndVersionNumber: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1FormsVersionsModelByFormIdAndVersionNumber', args.formId, args.versionNumber); },
    getV1Export: function () { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1Export'); },
    createV1Purge: function () { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'createV1Purge'); },
    getV1JobsByJobId: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'getV1JobsByJobId', args.jobId); },
    createV1Messages: function (args) { return new core_1.OpenApiRequestBuilder(api_1.DefaultApi, 'createV1Messages', args.body); }
};
//# sourceMappingURL=api.js.map