name: 'Fixed version bump'
description: 'Bumps version for fixed packages and the root package.json using changests.'
outputs:
  version:
    description: 'The new version'
runs:
  using: 'node20'
  main: 'index.js'
