/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Test Service
 * Test Service for OpenApi version 2 aka. Swagger as YAML file.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TestEntity } from '../model';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Test PATCH
         * @param {string} pathParam 
         * @param {TestEntity} [testEntity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchEntity: async (pathParam: string, testEntity?: TestEntity, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'pathParam' is not null or undefined
            if (pathParam === null || pathParam === undefined) {
                throw new RequiredError('pathParam','Required parameter pathParam was null or undefined when calling patchEntity.');
            }
            const localVarPath = `/entities/{pathParam}`
                .replace(`{${"pathParam"}}`, encodeURIComponent(String(pathParam)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof testEntity !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(testEntity !== undefined ? testEntity : {})
                : (testEntity || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test POST
         * @summary Test POST
         * @param {string} pathParam 
         * @param {string} [queryParam] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEntity: async (pathParam: string, queryParam?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'pathParam' is not null or undefined
            if (pathParam === null || pathParam === undefined) {
                throw new RequiredError('pathParam','Required parameter pathParam was null or undefined when calling postEntity.');
            }
            const localVarPath = `/entities/{pathParam}`
                .replace(`{${"pathParam"}}`, encodeURIComponent(String(pathParam)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (queryParam !== undefined) {
                localVarQueryParameter['queryParam'] = queryParam;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Test PATCH
         * @param {string} pathParam 
         * @param {TestEntity} [testEntity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchEntity(pathParam: string, testEntity?: TestEntity, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).patchEntity(pathParam, testEntity, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test POST
         * @summary Test POST
         * @param {string} pathParam 
         * @param {string} [queryParam] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEntity(pathParam: string, queryParam?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TestEntity>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).postEntity(pathParam, queryParam, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Test PATCH
         * @param {string} pathParam 
         * @param {TestEntity} [testEntity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchEntity(pathParam: string, testEntity?: TestEntity, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).patchEntity(pathParam, testEntity, options).then((request) => request(axios, basePath));
        },
        /**
         * Test POST
         * @summary Test POST
         * @param {string} pathParam 
         * @param {string} [queryParam] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEntity(pathParam: string, queryParam?: string, options?: any): AxiosPromise<Array<TestEntity>> {
            return DefaultApiFp(configuration).postEntity(pathParam, queryParam, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Test PATCH
     * @param {string} pathParam 
     * @param {TestEntity} [testEntity] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public patchEntity(pathParam: string, testEntity?: TestEntity, options?: any) {
        return DefaultApiFp(this.configuration).patchEntity(pathParam, testEntity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Test POST
     * @summary Test POST
     * @param {string} pathParam 
     * @param {string} [queryParam] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postEntity(pathParam: string, queryParam?: string, options?: any) {
        return DefaultApiFp(this.configuration).postEntity(pathParam, queryParam, options).then((request) => request(this.axios, this.basePath));
    }
}
