name: auto-dependabot-fix

on:
  pull_request: ~

jobs:
  building:
    if: github.actor == 'dependabot[bot]' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
      - run: git fetch --depth=1
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Run Lint
        run: yarn lint:fix
      - name: Commit Changes if needed
        run: |
          diff=`git diff`
          if [ ! -z "$diff" ]; then
            git config --global user.email "cloud-sdk-js@github.com"
            git config --global user.name "cloud-sdk-js"
            git commit -m "Changes from lint:fix" -a
            git push
          fi
