name: auto-dependabot-fix

on:
  pull_request_target: ~

permissions: {}

jobs:
  building:
    permissions:
      contents: read
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.SAP_CLOUD_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_CLOUD_SDK_BOT_PRIVATE_KEY }}
          owner: SAP
          repositories: cloud-sdk-js
          permission-contents: write
      - uses: sap/cloud-sdk-js/.github/actions/setup@davidkna-sap/prio-package.json
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
          allow-unsafe-pr-checkout: true
      - name: Commit Changes if needed
        env:
          BOT_EMAIL: ${{ vars.SAP_CLOUD_SDK_BOT_EMAIL }}
          BOT_NAME: ${{ vars.SAP_CLOUD_SDK_BOT_NAME }}
        run: |
          diff=`git diff`
          if [ ! -z "$diff" ]; then
            git config --global user.email "$BOT_EMAIL"
            git config --global user.name "$BOT_NAME"
            git commit -m "Regenerate check-public-api action" -a
            git push
          fi
