name: blackduck-scan

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - run: sudo apt-get install jq
      - run: echo "project_version=$(cat package.json | jq '.version' | tr -d '"')" >> $GITHUB_ENV
      - name: Blackduck Scan
        uses: SAP/project-piper-action@43db6643d830b42717eda052300d87c22b0da73b
        with:
          command: detectExecuteScan
          flags: \
            --version=$PROJECT_VERSION \
            --excludedDirectories=test-packages
        env:
          PIPER_token: ${{ secrets.BLACKDUCK_TOKEN }}
          PROJECT_VERSION: ${{ env.project_version }}
          DETECT_TIMEOUT: 6000
          # DETECT_PNPM_EXCLUDED_WORKSPACES: test-packages/**
          DETECT_PNPM_DEPENDENCY_TYPES_EXCLUDED: NON_PRODUCTION
      - if: failure() || cancelled()
        name: Slack Notify
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: SDK Pipeline Bot
          SLACK_TITLE: Blackduck scan ${{ job.status }}
          SLACK_MESSAGE: 'Test failed'
          MSG_MINIMAL: event,actions url
          SLACK_COLOR: ${{ job.status }}
          SLACK_MSG_AUTHOR: ' '
          SLACK_ICON: https://sap.github.io/cloud-sdk/img/logo.png
