name: build v3

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ubuntu-latest-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn test:unit
        env:
          SANDBOX_TOKEN: ${{ secrets.API_HUB_SANDBOX_TOKEN }}
      - run: yarn test:integration
      - run: yarn test:self
      - run: yarn test:type
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn lint
        name: Static Code Check
      - run: yarn check:test-service
        name: Test Service Version Check
      - run: yarn check:dependencies
        name: Undeclared dependency Check
      - run: yarn check:public-api
        name: Check public api
      - run: yarn test:self
        name: Self tests for tools
      - run: yarn check:circular
        name: Circular dependency Check
      - run: yarn doc
        name: API Doc Check
      - run: yarn check:license
        name: License Check
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn test:e2e
