name: bump

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: Mandatory, when bumping a major version. Semver compatible version string (X.Y.Z). Must not be set for patch and minor version releases.
        required: false

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.SAP_CLOUD_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_CLOUD_SDK_BOT_PRIVATE_KEY }}
          owner: SAP
          repositories: cloud-sdk-js
          permission-contents: write
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: 'main'
          persist-credentials: true
      - uses: ./.github/actions/setup

      - name: bump version
        id: bump
        uses: ./.github/actions/changesets-fixed-version-bump
        with:
          majorVersion: ${{ inputs.majorVersion }}

      - run: pnpm exec ts-node ${{ github.workspace }}/scripts/update-documentation-md.ts
        env:
          NEXT_PACKAGE_VERSION: ${{ steps.bump.outputs.version }}

      - name: merge Changelogs
        id: merge-changelogs
        uses: ./.github/actions/merge-and-write-changelogs
        env:
          VERSION: ${{ steps.bump.outputs.version }}

      - name: commit and tag
        uses: ./.github/actions/commit-and-tag
        with:
          version: ${{ steps.bump.outputs.version }}
          user-email: ${{ vars.SAP_CLOUD_SDK_BOT_EMAIL }}
          user-name: ${{ vars.SAP_CLOUD_SDK_BOT_NAME }}

  generate-api-docs:
    name: Generate and Push API Documentation
    needs: [bump]
    uses: ./.github/workflows/api-docs.yml
    secrets: inherit
    with:
      version: v${{ needs.bump.outputs.version }}
