name: 'pr-check'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Collect changed files
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        id: changed-files
        with:
          files: |
            .changeset/**
      - uses: ./.github/actions/check-pr
        with:
          changed-files: ${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}
