name: downloads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions: {}

jobs:
  downloads:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@davidkna-sap/prio-package.json
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - name: Download Stats
        run: pnpm exec ts-node scripts/npm-stats.ts
