name: downloads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: pnpm exec ts-node scripts/npm-stats.ts
        name: Download Stats
