name: downloads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions: {}

jobs:
  downloads:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
      - name: Download Stats
        run: node scripts/npm-stats.ts
