name: 'Fosstars (Security)'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: 'Security rating'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: SAP/fosstars-rating-core-action@daf10c3920b53405f6013ee987e7015525fdec30 # v1.14.0
        with:
          report-branch: fosstars-report
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: failure() || cancelled()
        name: Slack Notify
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: SDK Pipeline Bot
          SLACK_TITLE: Fosstars scan ${{ job.status }}
          SLACK_MESSAGE: 'Test failed'
          MSG_MINIMAL: event,actions url
          SLACK_COLOR: ${{ job.status }}
          SLACK_MSG_AUTHOR: ' '
          SLACK_ICON: https://sap.github.io/cloud-sdk/img/logo.png
