name: memory-tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * *

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: pnpm --filter @sap-cloud-sdk/e2e-tests run pretest:e2e
        name: start e2e tests server
      - run: pnpm install
        name: install test v2
        working-directory: test-packages/memory-tests/sdk-v2/
      - run: pnpm exec generate-odata-client
        name: generate v2 test client
        working-directory: test-packages/memory-tests/sdk-v2/
      - run: node --inspect test-script.js && cat result.txt
        working-directory: test-packages/memory-tests/sdk-v2/
      - run: pnpm install
        name: install test canary
        working-directory: test-packages/memory-tests/sdk-canary/
      - run: pnpm exec generate-odata-client
        name: generate canary test client
        working-directory: test-packages/memory-tests/sdk-canary/
      - run: node --inspect test-script.js && cat result.txt
        working-directory: test-packages/memory-tests/sdk-canary/
      - run: pnpm exec ts-node scripts/compare-memory-usage.ts $(cat ./test-packages/memory-tests/sdk-v2/result.txt) $(cat ./test-packages/memory-tests/sdk-canary/result.txt)
        name: compare v2 and canary
      - if: failure() || cancelled()
        name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: SDK Pipeline Bot
          SLACK_TITLE: Memory tests ${{ job.status }}
          SLACK_MESSAGE: 'Test failed'
          MSG_MINIMAL: event,actions url
          SLACK_COLOR: ${{ job.status }}
          SLACK_MSG_AUTHOR: ' '
          SLACK_ICON: https://sap.github.io/cloud-sdk/img/logo.png
