name: 'Check PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commit:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          fix
          feat
          chore
          revert
      # - uses: ./.github/actions/check-pr
