# This workflow delegates to the appropriate release workflow based on the event that triggered it.
name: release-entry

on:
  # Triggers for official releases
  release:
    types: [published]
  # Triggers for canary releases
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      canary-release:
        description: 'Canary release'
        type: choice
        required: false
        default: 'With Tests and Checks'
        options:
          - 'With Tests and Checks'
          - 'Skip Tests and Checks (Force Release)'

permissions: {}

jobs:
  delegate_to_release_job:
    if: ${{ github.event_name == 'release' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/release.yml
    secrets:
      SAP_CLOUD_SDK_BOT_CLIENT_ID: ${{ secrets.SAP_CLOUD_SDK_BOT_CLIENT_ID }}
      SAP_CLOUD_SDK_BOT_PRIVATE_KEY: ${{ secrets.SAP_CLOUD_SDK_BOT_PRIVATE_KEY }}

  delegate_to_canary_job:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/build.yml
    secrets:
      NPM_TOKEN_ARTIFACTORY: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      canary-release-skip-checks: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.canary-release == 'Skip Tests and Checks (Force Release)' }}
      is-workflow-call: true
