name: release

on:
  workflow_call:
    secrets:
      SAP_CLOUD_SDK_BOT_CLIENT_ID:
        required: true
      SAP_CLOUD_SDK_BOT_PRIVATE_KEY:
        required: true

permissions: {}

jobs:
  stable-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.SAP_CLOUD_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_CLOUD_SDK_BOT_PRIVATE_KEY }}
          owner: SAP
          repositories: cloud-sdk
          permission-contents: write
          permission-pull-requests: write
      - uses: sap/cloud-sdk-js/.github/actions/setup@davidkna-sap_pnpm-fix-dbot
        with:
          ref: 'main'
          persist-credentials: true
          node-version: 24 # Will install npm 11 needed for trusted publishing
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: Legacy Release
        if: startsWith(github.ref, 'refs/tags/v1') || startsWith(github.ref, 'refs/tags/v2') || startsWith(github.ref, 'refs/tags/v3')
        run: |
          pnpm changeset publish --tag legacy
      - name: Latest Release
        if: startsWith(github.ref, 'refs/tags/v4')
        run: |
          pnpm changeset publish
      - name: Checkout Docs
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: SAP/cloud-sdk
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          path: ./cloud-sdk
          persist-credentials: true
      - name: Fetch full commit history (blobless)
        run: git fetch --filter=blob:none --unshallow
      - name: Update release notes
        run: |
          npx ts-node -e "import { addCurrentChangelog } from './scripts/add-changelog'; addCurrentChangelog()"
      - name: Open PR
        env:
          BOT_EMAIL: ${{ vars.SAP_CLOUD_SDK_BOT_EMAIL }}
          BOT_NAME: ${{ vars.SAP_CLOUD_SDK_BOT_NAME }}
        run: |

          git config user.email "$BOT_EMAIL"
          git config user.name "$BOT_NAME"

          cd cloud-sdk

          git checkout -b "update-release-notes"
          git commit -m "update release notes" -a
          git push -u origin update-release-notes

          PR_BODY="Auto-created by update release notes workflow."
          PR_TITLE="Update JS Release Notes"
          gh pr create --head "update-release-notes" --title "${PR_TITLE}" --body "${PR_BODY}"
