name: windows-tests

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - run: pnpm run test:unit
      - run: pnpm run test:integration
        if: always()
      - run: pnpm run test:self
      - run: pnpm run test:type
