name: typedoc-check

on:
  pull_request: ~
  push:
    branches: ['main']
    tags: ['v*']
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: pnpm run doc
