name: typedoc-check

on:
  pull_request: ~
  push:
    branches: ['main']
    tags: ['v*']
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - run: pnpm run doc
