name: v2-next-release

on:
  push:
    branches: [2.0]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ matrix.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn test:unit
        env:
          SANDBOX_TOKEN: ${{ secrets.API_HUB_SANDBOX_TOKEN }}
      - run: yarn test:integration
      - run: yarn test:type
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
        name: Static Code Check
      - run: yarn check:test-service
        name: Test Service Version Check
      - run: yarn check:dependencies
        name: Undeclared dependency Check
      - run: yarn check:circular
        name: Circular dependency Check
      - run: yarn doc
        name: API Doc Check
      - run: yarn check:license
        name: License Check
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn test:e2e
  canary-release:
    if: github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [tests, checks, e2e-tests]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - name: Canary Release
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          date=`date +%Y%m%d%H%M%S`
          yarn lerna publish --canary patch --no-push --no-git-tag-version --dist-tag next --force-publish --preid "beta.1-${date}" -y
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
